version: '3.7'

services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_HOST=db
    depends_on:
      - db
    networks:
      - internal

  db:
    image: mariadb
    container_name: nextcloud-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - db:/var/lib/mysql
    networks:
      - internal

  onlyoffice:
    image: onlyoffice/documentserver
    container_name: onlyoffice
    restart: always
    environment:
      - JWT_SECRET=$JWT_SECRET
    networks:
      - internal

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - nextcloud
      - onlyoffice
    networks:
      - proxy
      - internal

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'sleep 10 && certbot certonly --webroot -w /var/www/certbot --agree-tos --no-eff-email --email ${CERTBOT_EMAIL} -d ${NEXTCLOUD_DOMAIN} -d ${ONLYOFFICE_DOMAIN}'"

volumes:
  nextcloud:
  db:

networks:
  proxy:
  internal:
