server {
  listen 80;
  server_name nextcloud.automatiiz.net;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  location / {
    return 301 https://$host$request_uri;
  }
}

server {
  listen 443 ssl;
  server_name nextcloud.automatiiz.net;

  ssl_certificate /etc/letsencrypt/live/nextcloud.automatiiz.net/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/nextcloud.automatiiz.net/privkey.pem;

  location / {
    proxy_pass http://nextcloud:80;
    include /etc/nginx/proxy_params;
    proxy_redirect off;
  }
}
